###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "reader@user.com",
    "password": "reader"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "writer@user.com",
    "password": "writer"
}
