###
GET {{host}}/posts
Authorization: {{tokenReader}}

###
GET {{host}}/posts/cm92hkcf20001tas8um2yiqc2
Authorization: {{tokenReader}}

###
DELETE {{host}}/posts/cm91i13x50001tauw2nt6zttt
Authorization: {{tokenReader}}

###
POST {{host}}/posts
Authorization: {{tokenReader}}
Content-Type: application/json

{
    "title": "Title 7",
    "content": "Content 7",
    "published": false
}
