###
GET {{host}}/users
Authorization: {{tokenAdmin}}

###
GET {{host}}/users/me
Authorization: {{tokenReader}}

###
GET {{host}}/users/cm92hdtz50000ta50g5l7zhjc

###
DELETE {{host}}/users/cm92h5ppx0000taksedds6nqu

###
POST {{host}}/users
Authorization: {{tokenReader}}
Content-Type: application/json

{
	"name": "Admin",
	"email": "admin@user.com",
	"password": "admin",
	"permissions": [
		[
			"manage",
			"all"
		]
	],
	"role": "admin"
}

###
POST {{host}}/users
Authorization: {{tokenReader}}
Content-Type: application/json

{
	"name": "Reader 1",
	"email": "reader1@user.com",
	"password": "reader",
	"role": "reader"
}

###
POST {{host}}/users
Authorization: {{tokenReader}}
Content-Type: application/json

{
	"name": "Writer",
	"email": "writer@user.com",
	"password": "writer",
	"role": "writer"
}

###
PATCH {{host}}/users/cm92xnee00000tar8cg87m10i
Authorization: {{tokenReader}}
Content-Type: application/json

{
	"permissions": []
}
